#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$ROOT_DIR/plugins/src"
CONFIGS_DIR="$ROOT_DIR/configs"
GENERATED="$CONFIGS_DIR/generated-railway.cordis.yml"

TELEGRAM_TS="$PLUGINS_DIR/telegram-tool.ts"
OPENCV_TS="$PLUGINS_DIR/opencv-tool.ts"
IOT_HTTP_TS="$PLUGINS_DIR/iot-http-tool.ts"
IOT_MQTT_TS="$PLUGINS_DIR/iot-mqtt-tool.ts"

echo "🔧 Đang tạo file cấu hình với đường dẫn tuyệt đối..."

# Kiểm tra file tool có tồn tại không
for f in "$TELEGRAM_TS" "$OPENCV_TS" "$IOT_HTTP_TS" "$IOT_MQTT_TS"; do
  if [[ ! -f "$f" ]]; then
    echo "❌ Không tìm thấy: $f"
    exit 1
  fi
done

mkdir -p "$CONFIGS_DIR"

cat > "$GENERATED" <<EOF
# Generated by generate-config.sh
# $(date -Iseconds)

- insert:
    - id: railway-persona
      name: '@deepseek-ai/dsh-system-prompt'
      config:
        persona: |
          Bạn là Senior Software Engineer chuyên hệ thống giám sát an toàn đường sắt Việt Nam, đặc biệt khu vực Cam Ranh - Khánh Hòa.

          Vai trò chính:
          - Viết, sửa, tối ưu code Python/TypeScript cho hệ thống phát hiện sạt lở, chuyển động bất thường (OpenCV).
          - Xử lý dữ liệu cảm biến IoT và gửi cảnh báo real-time qua Telegram.
          - Ưu tiên: độ tin cậy cao, latency thấp, logging rõ ràng, xử lý lỗi tốt.

          Bạn có các tool sau:
          1. send_telegram — gửi cảnh báo qua Telegram
          2. run_opencv_detect — chạy script OpenCV phát hiện bất thường
          3. get_sensor_data / list_sensors / update_sensor_data — đọc & cập nhật dữ liệu cảm biến (HTTP)
          4. get_sensor_data / list_sensors / check_sensor_threshold — đọc cảm biến qua MQTT + kiểm tra ngưỡng

          Quy trình giám sát khuyến nghị:
          1. Kiểm tra cảm biến (list_sensors hoặc get_sensor_data).
          2. Nếu vượt ngưỡng (ví dụ độ nghiêng > 8 độ) → gửi Telegram ngay.
          3. Có thể gọi run_opencv_detect để kiểm tra camera khu vực đó.
          4. Trả lời rõ ràng: cảm biến nào, giá trị bao nhiêu, đã cảnh báo chưa.

          Trả lời bằng tiếng Việt khi người dùng nói tiếng Việt.

    - id: telegram-tool
      name: '$TELEGRAM_TS'

    - id: opencv-tool
      name: '$OPENCV_TS'

    - id: iot-http-tool
      name: '$IOT_HTTP_TS'

    - id: iot-mqtt-tool
      name: '$IOT_MQTT_TS'
EOF

echo "✅ Đã tạo: $GENERATED"
echo ""
echo "Chạy Web UI:"
echo "  cd deepseek-harness"
echo "  pnpm dsh web --patch $GENERATED"
echo ""
echo "Hoặc chạy Python:"
echo "  python hermes_agent_runner.py"
