#!/usr/bin/env bash
set -euo pipefail

# Script tự động tạo file cấu hình với đường dẫn tuyệt đối thật

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGINS_DIR="$ROOT_DIR/plugins"
CONFIGS_DIR="$ROOT_DIR/configs"
GENERATED="$CONFIGS_DIR/generated-railway.cordis.yml"

TELEGRAM_TS="$PLUGINS_DIR/src/telegram-tool.ts"
OPENCV_TS="$PLUGINS_DIR/src/opencv-tool.ts"

if [[ ! -f "$TELEGRAM_TS" || ! -f "$OPENCV_TS" ]]; then
  echo "❌ Không tìm thấy file tool. Kiểm tra lại cấu trúc thư mục."
  exit 1
fi

echo "🔧 Đang tạo file cấu hình với đường dẫn tuyệt đối..."

cat > "$GENERATED" <<EOF
# Generated by scripts/generate-config.sh
# $(date -Iseconds)

- insert:
    - id: railway-persona
      name: '@deepseek-ai/dsh-system-prompt'
      config:
        persona: |
          Bạn là Senior Software Engineer chuyên hệ thống giám sát an toàn đường sắt Việt Nam, đặc biệt khu vực Cam Ranh - Khánh Hòa.

          Vai trò chính của bạn:
          - Viết, sửa, tối ưu code Python và TypeScript cho hệ thống phát hiện sạt lở, chuyển động bất thường bằng OpenCV.
          - Xử lý dữ liệu cảm biến IoT và gửi cảnh báo real-time qua Telegram.
          - Ưu tiên: độ tin cậy cao, latency thấp, logging rõ ràng, xử lý lỗi tốt, code dễ bảo trì.
          - Khi làm việc với camera/sensor: luôn cân nhắc điều kiện thực tế (ánh sáng yếu, mưa, rung lắc, bụi).
          - Trước khi kết thúc task, hãy mô tả cách kiểm tra hoặc chạy test nếu có thể.
          - Trả lời bằng tiếng Việt khi người dùng giao tiếp bằng tiếng Việt. Comment trong code ưu tiên tiếng Anh rõ ràng.

          Bạn có sẵn 2 tool đặc biệt:
          1. send_telegram — gửi cảnh báo qua Telegram
          2. run_opencv_detect — chạy script OpenCV phát hiện bất thường

          Hãy chủ động sử dụng các tool này khi phù hợp.

    - id: telegram-tool
      name: '$TELEGRAM_TS'

    - id: opencv-tool
      name: '$OPENCV_TS'
EOF

echo "✅ Đã tạo: $GENERATED"
echo ""
echo "Bạn có thể chạy Web UI bằng lệnh:"
echo "  cd deepseek-harness"
echo "  pnpm dsh web --patch $GENERATED"
echo ""
echo "Hoặc chạy Python runner:"
echo "  python hermes_agent_runner.py"
