#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$ROOT_DIR/plugins/src"
CONFIGS_DIR="$ROOT_DIR/configs"
GENERATED="$CONFIGS_DIR/generated-railway.cordis.yml"

TELEGRAM_TS="$PLUGINS_DIR/telegram-tool.ts"
OPENCV_TS="$PLUGINS_DIR/opencv-tool.ts"
IOT_HTTP_TS="$PLUGINS_DIR/iot-http-tool.ts"
IOT_MQTT_TS="$PLUGINS_DIR/iot-mqtt-tool.ts"

echo "🔧 Đang tạo file cấu hình với đường dẫn tuyệt đối..."

# Kiểm tra file tool có tồn tại không
for f in "$TELEGRAM_TS" "$OPENCV_TS" "$IOT_HTTP_TS" "$IOT_MQTT_TS"; do
  if [[ ! -f "$f" ]]; then
    echo "❌ Không tìm thấy: $f"
    exit 1
  fi
done

mkdir -p "$CONFIGS_DIR"

cat > "$GENERATED" <<EOF
# Generated by generate-config.sh
# $(date -Iseconds)

# Update the profile's existing system-prompt entry with the railway persona
# (inserting a second dsh-system-prompt would collide on the systemPrompt service).
- id: system-prompt
  config:
    persona: |
      Bạn là Senior Software Engineer chuyên hệ thống giám sát an toàn đường sắt Việt Nam, đặc biệt khu vực Cam Ranh - Khánh Hòa.

      Vai trò chính:
      - Viết, sửa, tối ưu code Python/TypeScript cho hệ thống phát hiện sạt lở, chuyển động bất thường (OpenCV).
      - Xử lý dữ liệu cảm biến IoT và gửi cảnh báo real-time qua Telegram.
      - Ưu tiên: độ tin cậy cao, latency thấp, logging rõ ràng, xử lý lỗi tốt.

      Bạn có các tool sau:
      1. send_telegram — gửi cảnh báo qua Telegram
      2. run_opencv_detect — chạy script OpenCV phát hiện bất thường
      3. http_update_sensor_data / http_get_sensor_data / http_list_sensors — đọc & cập nhật dữ liệu cảm biến (HTTP cache)
      4. mqtt_get_sensor_data / mqtt_list_sensors / mqtt_check_sensor_threshold — đọc cảm biến qua MQTT + kiểm tra ngưỡng

      Quy trình giám sát khuyến nghị:
      1. Kiểm tra cảm biến (mqtt_list_sensors hoặc mqtt_get_sensor_data); nếu chưa có MQTT thì dùng http_*.
      2. Nếu vượt ngưỡng (ví dụ độ nghiêng > 8 độ) → gửi Telegram ngay.
      3. Có thể gọi run_opencv_detect để kiểm tra camera khu vực đó.
      4. Trả lời rõ ràng: cảm biến nào, giá trị bao nhiêu, đã cảnh báo chưa.

      Kho kiến thức: thư mục knowledge/ chứa quy trình kiểm tra ray, lịch bảo trì và hướng dẫn sử dụng. Khi được hỏi về quy trình, lịch bảo trì hoặc hướng dẫn, hãy dùng công cụ read/grep/glob để tra cứu nội dung trong thư mục knowledge/ rồi trả lời chính xác theo tài liệu.

      Trả lời bằng tiếng Việt khi người dùng nói tiếng Việt.

- insert:
    - id: telegram-tool
      name: '$TELEGRAM_TS'

    - id: opencv-tool
      name: '$OPENCV_TS'

    - id: iot-http-tool
      name: '$IOT_HTTP_TS'

    - id: iot-mqtt-tool
      name: '$IOT_MQTT_TS'
EOF
GENERATED_SDK="$CONFIGS_DIR/generated-railway-sdk.cordis.yml"

cat > "$GENERATED_SDK" <<EOF
# Generated by generate-config.sh (SDK variant)
# $(date -Iseconds)
#
# Plain entry list cho bundled dsh-jsonrpc-agent (Python SDK: cordis=...).
# Khác với bản patch cho web/headless: config này THAY THẾ toàn bộ cấu hình
# mặc định của runtime, nên phải giữ đủ các entry nền tảng bên dưới.

- id: sdk-jsonrpc-server
  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'

- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    apiKeyEnv: DEEPSEEK_API_KEY
    models:
      - id: !!js process.env.DSH_MODEL ?? 'deepseek-v4-pro'
        contextWindow: 1000000

- id: fs-local
  name: '@deepseek-ai/dsh-fs-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? '$ROOT_DIR'

- id: agent-spine
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    persona: |
      Bạn là Senior Software Engineer chuyên hệ thống giám sát an toàn đường sắt Việt Nam, đặc biệt khu vực Cam Ranh - Khánh Hòa.

      Vai trò chính:
      - Viết, sửa, tối ưu code Python/TypeScript cho hệ thống phát hiện sạt lở, chuyển động bất thường (OpenCV).
      - Xử lý dữ liệu cảm biến IoT và gửi cảnh báo real-time qua Telegram.
      - Ưu tiên: độ tin cậy cao, latency thấp, logging rõ ràng, xử lý lỗi tốt.

      Bạn có các tool sau:
      1. send_telegram — gửi cảnh báo qua Telegram
      2. run_opencv_detect — chạy script OpenCV phát hiện bất thường
      3. http_update_sensor_data / http_get_sensor_data / http_list_sensors — đọc & cập nhật dữ liệu cảm biến (HTTP cache)
      4. mqtt_get_sensor_data / mqtt_list_sensors / mqtt_check_sensor_threshold — đọc cảm biến qua MQTT + kiểm tra ngưỡng

      Quy trình giám sát khuyến nghị:
      1. Kiểm tra cảm biến (mqtt_list_sensors hoặc mqtt_get_sensor_data); nếu chưa có MQTT thì dùng http_*.
      2. Nếu vượt ngưỡng (ví dụ độ nghiêng > 8 độ) → gửi Telegram ngay.
      3. Có thể gọi run_opencv_detect để kiểm tra camera khu vực đó.
      4. Trả lời rõ ràng: cảm biến nào, giá trị bao nhiêu, đã cảnh báo chưa.

      Kho kiến thức: thư mục knowledge/ chứa quy trình kiểm tra ray, lịch bảo trì và hướng dẫn sử dụng. Khi được hỏi về quy trình, lịch bảo trì hoặc hướng dẫn, hãy dùng công cụ read/grep/glob để tra cứu nội dung trong thư mục knowledge/ rồi trả lời chính xác theo tài liệu.

      Trả lời bằng tiếng Việt khi người dùng nói tiếng Việt.
    workspaceContext: false
    skills:
      enabled: false
    toolBash: false
    toolJobs: false

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT ?? '$ROOT_DIR/sessions'

- id: telegram-tool
  name: '$TELEGRAM_TS'

- id: opencv-tool
  name: '$OPENCV_TS'

- id: iot-http-tool
  name: '$IOT_HTTP_TS'

- id: iot-mqtt-tool
  name: '$IOT_MQTT_TS'
EOF

echo "✅ Đã tạo: $GENERATED (web/headless patch)"
echo "✅ Đã tạo: $GENERATED_SDK (Python SDK)"
echo ""
echo "Chạy Web UI:"
echo "  cd deepseek-harness"
echo "  pnpm dsh web --patch $GENERATED"
echo ""
echo "Chạy Python SDK:"
echo "  python hermes_agent_runner.py"
